version: "3.8"

services:
  fastapi:
    build: .
    container_name: fastapi
    environment:
      - MINIO_ENDPOINT=host.docker.internal:9000  # Access existing MinIO
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    ports:
      - "8000:8000"
    depends_on:
      - streamlit
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  streamlit:
    build: .
    container_name: streamlit
    environment:
      - API_URL=http://fastapi:8000
      - MINIO_ENDPOINT=host.docker.internal:9000  # Access existing MinIO
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    ports:
      - "8501:8501"
    command: streamlit run streamlit_dashboard.py --server.port 8501 --server.address 0.0.0.0
